
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
#installs and configures haproxy
- hosts: HAproxy
  become: yes
  become_method: sudo
  tasks:
    - name: HAproxy Update
      apt:
        update_cache: yes

    - name: Install HAproxy
      apt:
        name: haproxy
        state: latest

    - name: Configure HAproxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg.j2
 
    - name: Restart HAproxy
      become: yes
      service:
        name: haproxy
        state: restarted

# Deploys and tests the flask app on webservers
- hosts: webservers
  become: yes
  become_method: sudo
  tasks:

    - name: Webservers update
      apt:
        update_cache: yes

    - name: install python3-pip
      apt:
        name: python3-pip
        state: latest
        update_cache: yes

    - name: flask installation
      pip:
        name: flask
        state: latest

    - name: install Gunicorn
      apt:
        name: gunicorn

    - name: copy the flask app code to the servers
      copy:
        src:  /$PWD/application2.py
        dest: /home/ubuntu/application2.py
        owner: ubuntu
        mode: '0644'
           
    - name: execute the flask-app deployment
      shell: gunicorn -w 2 -D -b 0.0.0.0:8080 application2:app
 
- hosts: HAproxy
  become: yes
  become_method: sudo
  tasks:       
    - name: Restart HAproxy
      become: yes
      service:
            name: haproxy
            state: restarted
